Repository su25-it115-it161-class/su25-it115-it161-class.github.io, pull requests merged in 2025-08, with the labels that each got.

#29 PR: 11 feat create html structure for a single student profile
  about.html
  css/style.css
  index.html
  students.html
  students/images/studentname.png
Labels: enhancement

#32 Feature/add homepage buttons #issues 10
  css/style.css
  index.html
Labels: enhancement

#35 Issue #12 & Issue #13 - CSS to Student cards/template
  css/style.css
Labels: enhancement

#68 #39 Remove margins from headers and footers
  css/style.css
  index.html
Labels: enhancement

#63 #20 docs: create a detailed readmemd for the project
  README.md
  css/README.txt
  images/README.txt
Labels: documentation

#82 Amber: Student Page #62
  students.html
  students/amberr.html
  students/images/Amber.png
Labels: documentation

#81 BUG: Margins on student and about pages #70
  about.html
  css/style.css
Labels: bug
